---
#
# Personnalisation du Site
# !!!Ne pas changer le nom et déplacer ce fichier
#
params:
  title : "BiVOUAC"
  subtitle: "www.billerot.eu"

  # l'icône dans l'onglet du navigateur
  favicon: "/site/bivouac.jpg"

  # l'image arrondie dans la carte du sommaire
  avatar: "/site/bivouac.jpg"

  # l'image d'arrière plan du site v3
  backgroundImage: "/site/pexels-irina-iriser-2781760.jpg"
  
# Menu Links et Navigation
menu:
#  links:
#  - name: "Foire en images"
#    url: "/foire/foire-en-images/"
#    weight: 10
  navigation:
  - name: "Documentation sur le thème BeeDream"
    url: "https://beedream.billerot.eu/"
    weight: 10
    pre: "help"
    Params:
      icon: "help"  
---